package main

import (
	"embed"
	"flag"
	"fmt"
	"io/fs"
	"log"
	"net/http"

	"github.com/debdut/Resoorch/pkg/routes/api"
)

//go:embed all:app
var nextFS embed.FS

func main() {
	port := *flag.Int("port", 80, "port to serve")
	flag.Parse()

	// Root at the `dist` folder generated by the Next.js app.
	distFS, err := fs.Sub(nextFS, "app")
	if err != nil {
		log.Fatal(err)
	}

	// The static Next.js app will be served under `/`.
	http.Handle("/", http.FileServer(http.FS(distFS)))
	// The API will be served under `/api`.
	http.HandleFunc("/api/", api.Handle)

	// Start HTTP server at port.
	log.Printf("Starting HTTP server at http://localhost:%d ...\n", port)
	err = http.ListenAndServe(
		fmt.Sprintf(":%d", port),
		nil,
	)
	if err != nil {
		log.Fatal(err)
	}
}
